import { promises as fs } from "fs";
import net from "net";
import path from "path";

/** A profile that can be supervised by the Proton proxy. */
export type TunnelProtocol = "openvpn" | "wireguard";

export interface TunnelProfile {
	configPath: string;
	configName: string;
	protocol: TunnelProtocol;
	/** The first IPv4 address declared by a WireGuard profile, when present. */
	interfaceIp?: string;
	/** The IPv4 CIDR to assign to the WireGuard interface, when present. */
	interfaceAddress?: string;
	/** Optional WireGuard interface MTU. */
	mtu?: number;
}

interface ParsedWireGuardProfile {
	interfaceIp?: string;
	interfaceAddress?: string;
	mtu?: number;
	hasPrivateKey: boolean;
	hasPeer: boolean;
}

const CONFIG_EXTENSIONS = new Set([".ovpn", ".conf"]);
const WIREGUARD_INTERFACE_KEYS = new Set(["PrivateKey", "ListenPort", "FwMark"]);
const WIREGUARD_PEER_KEYS = new Set([
	"PublicKey",
	"PresharedKey",
	"AllowedIPs",
	"Endpoint",
	"PersistentKeepalive",
	"ProtocolVersion",
]);

function withoutComment(line: string): string {
	// WireGuard comments start at the beginning of a line in all profiles
	// generated by Proton. Do not split values on '#': a key or endpoint value
	// is opaque to this parser and must reach `wg setconf` unchanged.
	return line.trim();
}

function parseAssignment(line: string): { key: string; value: string } | undefined {
	const separator = line.indexOf("=");
	if (separator < 0) return undefined;
	const key = line.slice(0, separator).trim();
	const value = line.slice(separator + 1).trim();
	if (!key || !value) return undefined;
	return { key, value };
}

function parseWireGuardProfile(content: string): ParsedWireGuardProfile | undefined {
	let section = "";
	let hasInterface = false;
	let hasPeer = false;
	let hasPrivateKey = false;
	let interfaceIp: string | undefined;
	let interfaceAddress: string | undefined;
	let mtu: number | undefined;

	for (const rawLine of content.split(/\r?\n/)) {
		const line = withoutComment(rawLine);
		if (!line || line.startsWith("#") || line.startsWith(";")) continue;
		const sectionMatch = /^\[([^\]]+)\]$/.exec(line);
		if (sectionMatch) {
			section = sectionMatch[1].trim().toLowerCase();
			if (section === "interface") hasInterface = true;
			if (section === "peer") hasPeer = true;
			continue;
		}
		const assignment = parseAssignment(line);
		if (!assignment) continue;
		if (section === "interface") {
			if (assignment.key === "PrivateKey") hasPrivateKey = true;
			if (assignment.key === "Address" && !interfaceIp) {
				for (const candidate of assignment.value.split(",")) {
					const normalized = candidate.trim();
					const address = normalized.split("/", 1)[0];
					if (net.isIPv4(address)) {
						interfaceIp = address;
						interfaceAddress = normalized.includes("/") ? normalized : `${normalized}/32`;
						break;
					}
				}
			}
			if (assignment.key === "MTU") {
				const parsed = Number(assignment.value);
				if (Number.isSafeInteger(parsed) && parsed >= 576 && parsed <= 65_535) mtu = parsed;
			}
		}
	}

	if (!hasInterface || !hasPeer || !hasPrivateKey) return undefined;
	return { interfaceIp, interfaceAddress, mtu, hasPrivateKey, hasPeer };
}

function looksLikeOpenVpn(content: string): boolean {
	// OpenVPN profiles are intentionally recognized by their directives rather
	// than by their filename. Proton occasionally downloads profiles as `.conf`.
	// Requiring both a client/remote directive and a tunnel/device directive
	// prevents arbitrary files in the mounted directory from being executed.
	const hasRemote = /(^|\n)\s*remote(?:\s|$)/m.test(content);
	const hasClient = /(^|\n)\s*client(?:\s|$)/m.test(content);
	const hasDevice = /(^|\n)\s*(?:dev|dev-type|proto|auth-user-pass)(?:\s|$)/m.test(content);
	return hasRemote && (hasClient || hasDevice);
}

/**
 * Return only directives understood by `wg setconf`.
 *
 * `wg-quick` profiles also contain Address/DNS/MTU and optional shell hooks.
 * We deliberately strip those here instead of invoking profile hooks or
 * allowing a downloaded file to execute arbitrary commands in the container.
 */
export function stripWireGuardConfig(content: string): string {
	let section = "";
	const output: string[] = [];
	for (const rawLine of content.split(/\r?\n/)) {
		const line = withoutComment(rawLine);
		if (!line || line.startsWith("#") || line.startsWith(";")) continue;
		const sectionMatch = /^\[([^\]]+)\]$/.exec(line);
		if (sectionMatch) {
			section = sectionMatch[1].trim();
			if (section.toLowerCase() === "interface" || section.toLowerCase() === "peer") output.push(`[${section}]`);
			else section = "";
			continue;
		}
		const assignment = parseAssignment(line);
		if (!assignment) continue;
		if (section.toLowerCase() === "interface" && WIREGUARD_INTERFACE_KEYS.has(assignment.key)) {
			output.push(`${assignment.key} = ${assignment.value}`);
		}
		if (section.toLowerCase() === "peer" && WIREGUARD_PEER_KEYS.has(assignment.key)) {
			output.push(`${assignment.key} = ${assignment.value}`);
		}
	}
	return `${output.join("\n")}\n`;
}

/**
 * Discover supported OpenVPN and WireGuard profiles in deterministic order.
 * Unsupported files are ignored with a diagnostic; a completely empty or
 * invalid directory fails closed with an actionable error.
 */
export async function listTunnelProfiles(configDirectory: string): Promise<TunnelProfile[]> {
	const entries = await fs.readdir(configDirectory).catch(() => [] as string[]);
	const profiles: TunnelProfile[] = [];
	const ignored: string[] = [];

	for (const entry of entries.sort((left, right) => left.localeCompare(right))) {
		if (!CONFIG_EXTENSIONS.has(path.extname(entry).toLowerCase())) continue;
		const configPath = path.join(configDirectory, entry);
		let content: string;
		try {
			const stat = await fs.stat(configPath);
			if (!stat.isFile()) continue;
			content = await fs.readFile(configPath, "utf8");
		} catch (error) {
			console.warn(`[config] ignoring unreadable profile ${entry}: ${error instanceof Error ? error.message : String(error)}`);
			ignored.push(entry);
			continue;
		}

		const wireGuard = parseWireGuardProfile(content);
		if (wireGuard) {
			profiles.push({
				configPath,
				configName: entry,
				protocol: "wireguard",
				interfaceIp: wireGuard.interfaceIp,
				interfaceAddress: wireGuard.interfaceAddress,
				mtu: wireGuard.mtu,
			});
			continue;
		}
		if (looksLikeOpenVpn(content)) {
			profiles.push({ configPath, configName: entry, protocol: "openvpn" });
			continue;
		}
		ignored.push(entry);
	}

	if (ignored.length) console.warn(`[config] ignored ${ignored.length} unsupported/unreadable profile file(s): ${ignored.join(", ")}`);
	if (!profiles.length) {
		throw new Error(`No supported OpenVPN (.ovpn/.conf) or WireGuard (.conf) configurations found in ${configDirectory}`);
	}
	return profiles;
}
